#!/usr/bin/env bash
# Displays superstitious messages for numbers 4, 9, and 17 using a case statement.
COUNT=1
while [ $COUNT -le 20 ]; do
echo "$COUNT"
case $COUNT in
4) echo "bad luck from China" ;;&nbsp;
9) echo "bad luck from Japan" ;;&nbsp;
17) echo "bad luck from Italy" ;;&nbsp;
esac
COUNT=$((COUNT + 1))
done
